### ISSUE TITLE
It's not working ( sometimes)

### ISSUE THREAD

**Issue by lilcheti** [TheDavidDelta/kainet-music#12]
Why it's not working Is there a restrict on scraper side?
why don't you use piped api for at least youtube alone

**Comment by thedaviddelta** [comment]
Hello and thanks for your interest in this project.

The app is experiencing some big problems with the audio fetching, as I explain more verbosely on #6, but it went to worse and now nearly no song is working, as you have noticed.

I have to make a final working decision and implement it when I have a bit of time.

And, what do you mean exactly with *piped api*?

Regards, David.

**Comment by lilcheti** [comment]
https://github.com/TeamPiped/Piped
https://piped-docs.kavin.rocks/docs/api-documentation/
I meant this You can get the audio out of the music videos I think it's a good workaround at least for now?

**Comment by thedaviddelta** [comment]
Oh, I see.

The problem with the audio source isn't on the info scraping side but on the media scraping side.
I would recommend you reading the previously linked issue in order to understand it, but in summary the problem comes with regionally availability of DRM content, as the server is in a different location that the user.

The approach Invidious takes (and I'm sure that Piped does the same) is to simply ignore the problem because it doesn't bother them very much, as there is very few DRM-based content on YouTube. But that's not the case for YouTube Music, where literally every song has DRM.

One of the self-proposed solutions in that linked issue is exactly that one, to ignore and let the media fail if the user is on a different location, letting the duty of avoiding that on the instance owners. And I'll probably end up going through that one.

And about the API you linked, it's for info scraping, not for media scraping, just like the [Invidious API](https://docs.invidious.io/API.md), the [NewPipe Extractor](https://github.com/TeamNewPipe/NewPipeExtractor) or our own [Kainet Scraper](https://github.com/TheDavidDelta/kainet-scraper). As I said that's the part that works, and we have our own FOSS library in order to do that (and with YTMusic support).

Thanks for trying to help, and for letting me know Piped. Didn't know the project, and it seems like a more beautiful Invidious.

Regards, David.

**Comment by lilcheti** [comment]
Umm it actually sends the media too, hls url plus video and audio urls. Idk what exactly you mean by the media though...
I had another idea of using telegram as a storage and using Deezer to download songs to telegram and build something like what you did. Can I have your matrix id to talk about it more maybe?
I'm really interested in what you are doing :)

**Comment by thedaviddelta** [comment]
Sure, it's [thedaviddelta@matrix.org](https://matrix.to/#/@thedaviddelta:matrix.org).
